# Sigmoid Assignment

In [1]:
#Importing the libraries
import numpy as np 
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import  mean_squared_error,accuracy_score
import matplotlib.pyplot as plt
from tqdm import tqdm

In [2]:
class SigmoidNeuron:
    def __init__(self):
        self.w = None
        self.b = None
    
    def sigmoid(self, x):
        weighted_sum = np.dot(self.w,x) + self.b
        return 1.0/(1.0 +(np.exp(-(weighted_sum))))
    
    def grad_w(self, x, y):
        y_pred = self.sigmoid(x)
        return (y_pred - y) * y_pred * (1 - y_pred) * x
    
    def grad_b(self, x, y):
        y_pred = self.sigmoid(x)
        return (y_pred - y) * y_pred * (1 - y_pred)
    
           
    def fit(self, X, Y, epochs=1, lr=1, initialize=True):
    
        # initialise w, b
        if initialize:
            np.random.seed(6)
            self.w = np.random.randn(1, X.shape[1])
            self.b = 0
        
        plot_loss = {}
        for i in tqdm(range(epochs), total = epochs, unit = 'epoch'):
            dw = 0
            db = 0
            for x, y in zip(X, Y):               
                dw += self.grad_w(x, y)
                db += self.grad_b(x, y)               

            self.w -= lr * dw
            self.b -= lr * db
            plot_loss[i] = self.Loss(X,Y)
        
        plt.plot(plot_loss.values())
        plt.xlabel("epochs")
        plt.ylabel("Loss")
        plt.show()
            

            
    def predict(self, X):
        Y_pred = []
        for x in X:
            y_pred = self.sigmoid(x)
            Y_pred.append(y_pred)
        return np.array(Y_pred)
    

    
    def Loss(self,X,Y):
        loss = 0
        Y_pred = self.predict(X)
        loss = mean_squared_error(Y,Y_pred)
        return loss
    
    def accuracy_value(self, X, Y, threshold=0.5):
        Y_pred = self.predict(X)
        Y_pred = (Y_pred >= threshold).astype(int)
        accuracy = accuracy_score(Y_pred, Y)
        return accuracy

# Importing the data

In [3]:
#importing the file
#This will download the file to google colab local drive, 
#else you can load manually in your jupyter notebook by skipping this line
!wget = https://www.dropbox.com/s/qhezagq0uwps7be/diabetes.csv

'wget' is not recognized as an internal or external command,
operable program or batch file.

In [4]:
#data used - https://www.kaggle.com/uciml/pima-indians-diabetes-database
data = pd.read_csv("diabetes.csv")

In [5]:
data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [6]:
data.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

# Assignment Steps

In [ ]:
'''
    1.Separate input and output data. The column - Outcome contains the output data.
    2.Split the data into Train and Test data - using random_state = 6
    3. Apply Standard Scalar on Training data
    4. Fit the data to Sigmoid model with 10 epochs and learning rate = 1
    5. Note down the Loss and Accuracy of model at step 4
    6. Fit the data to Sigmoid model with 100 epochs with learning rate = 1 for training data
    7. Note down the Loss and Accuracy of model at step 6
    8. Fit the data to Sigmoid model with 100 epochs with learning rate = 0.25 for training data
    9. Note down the Loss and Accuracy of model at step 8
    10. Fit the data to Sigmoid model with 1000 epochs with learning rate = 0.25 for training data
    11. Note down the Loss and Accuracy of model at step 10
    12. Fit the data to Sigmoid model with 10000 epochs with learning rate = 0.25 for training data
    13. Note down the Loss and Accuracy of model at step 12
    14. Compute the accuracy on the test data after step 12
''';